apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: my-port
  selector:
    app.kubernetes.io/name: helloworld

